[package]
name = "rally-python-rust-mpsc"
version = "0.0.1"
edition = "2024"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
name = "rally_python_rust_mpsc"
crate-type = ["cdylib"]

[dependencies]
pyo3 = "0.23.3"
